language: perl
before_install:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_4b7a7054081f_key -iv $encrypted_4b7a7054081f_iv -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
install:
- sudo apt-get install latexml
script:
- perl render.pl
- chmod 600 .travis/deploy_key.pem
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key.pem
- git config user.email "omniavinco@gmail.com"
- git config user.name "Gyusun Yeom"
- git config push.default simple
- git remote add deploy git@github.com:Perlmint/perlmint.github.io.git
- git fetch deploy
- git checkout -b gh-pages deploy/gh-pages || git checkout --orphan gh-pages
- git reset
- git rm --ignore-unmatch -q -r -f resume
- find . -name "*.html" -exec git rm --ignore-unmatch -q {} \;
- mv out/* .
- rm -rf out
- git add resume *.html *.css 
- if [ `git diff --cached | wc -l` -ne 0 ] ; then  git commit -m"Static page generated" && git push deploy; fi
